@baseUrl = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwianRpIjoiZWY1NzBjODYtNjFhYi00NDg0LTg1ODktNmIzYjM2ODExZDZkIiwibmJmIjoxNzYyNzgzMjE2LCJleHAiOjE3NjI3OTA0MTYsImlhdCI6MTc2Mjc4MzIxNn0.nXqJqmvJ1Mp3xxhMBeH6_6PVynC8O4AxdUm2v0mnB-s

### Get all quizzes
GET {{baseUrl}}/api/Quiz
Authorization: Bearer {{token}}
Accept: application/json

### Get quiz by id
GET {{baseUrl}}/api/Quiz/1
Authorization: Bearer {{token}}
Accept: application/json

### Create a quiz (admin)
POST {{baseUrl}}/api/Quiz
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Exemple de quiz",
  "categoryId": 1
}

### Update a quiz (admin)
PUT {{baseUrl}}/api/Quiz/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "title": "Quiz mis à jour",
  "categoryId": 1
}

### Delete a quiz (admin)
DELETE {{baseUrl}}/api/Quiz/1
Authorization: Bearer {{token}}

