@baseUrl = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwicm9sZSI6ImFkbWluIiwianRpIjoiMzRjOWIyZGUtYmJiOC00NmI4LWI3OTMtNWUwOTk4MDFmY2ZlIiwibmJmIjoxNzY0Njg5NzExLCJleHAiOjE3NjQ2OTY5MTEsImlhdCI6MTc2NDY4OTcxMX0.kUQEyEHj2BUDcaWAe5JKZJg1L4Epth1RWfWWTVvQZI0

### Start a quiz
GET {{baseUrl}}/api/Quiz/StartQuiz?userId=1&categoryId=1
Authorization: Bearer {{token}}
Accept: application/json

