@ElixBackend_HostAddress = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwicm9sZSI6ImFkbWluIiwianRpIjoiZjk5YThlOTktMjIxMC00Mjg2LTkwY2ItNGMwZWJlZDdjODJkIiwibmJmIjoxNzYyNzgyOTM5LCJleHAiOjE3NjI3OTAxMzksImlhdCI6MTc2Mjc4MjkzOX0.gzDMcSWR0xGct_ki0Gnp_6VwmDvfXF0fRiBXLPB2ECs

### LOGIN
POST {{ElixBackend_HostAddress}}/api/User/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "MotDePasse123"
}

###

### REGISTER
POST {{ElixBackend_HostAddress}}/api/User/register
Content-Type: application/json

{
  "email": "us1er@email.com",
  "password": "MotDePasse123",
  "passwordRepeated": "MotDePasse123",
  "firstname": "John",
  "lastname": "Doe",
  "username": "johndoe1",
  "birthdate": "2000-01-01T00:00:00",
  "gender": 0,
  "isPremium": false,
  "phoneNumber": 123456789,
  "isAdmin": true
}

###

### GET USER BY ID (auth)
GET {{ElixBackend_HostAddress}}/api/User/2
Authorization: Bearer {{token}}

###

### UPDATE USER (auth)
PUT {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "email": "user@email.com",
  "password": "MotDePasse123",
  "passwordRepeated": "MotDePasse123",
  "firstname": "John",
  "lastname": "Doe",
  "username": "johndoe",
  "birthdate": "2000-01-01T00:00:00",
  "gender": 0,
  "isPremium": false,
  "phoneNumber": 123456789,
  "isAdmin": false
}

###

### DELETE USER (auth)
DELETE {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}

###

### LOGOUT (auth)
POST {{ElixBackend_HostAddress}}/api/User/logout
Authorization: Bearer {{token}}

###