@ElixBackend_HostAddress = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIzIiwicm9sZSI6ImFkbWluIiwianRpIjoiYzI1YjQyZmEtMDQ0Yi00NGI3LTliNTktNTI4MTZmM2I1YmQ5IiwibmJmIjoxNzcwMzcyNjQ2LCJleHAiOjE3NzAzNzk4NDYsImlhdCI6MTc3MDM3MjY0Nn0.dpUOFfCDXfH9M8qbbvEUjEAlyJsJJYwHcQ5Aq5K9GqE

### LOGIN
POST {{ElixBackend_HostAddress}}/api/User/login
Content-Type: application/json

{
  "email": "augustinseguin@gmail.com",
  "password": "MotDePasse123"
}

###

### REGISTER
POST {{ElixBackend_HostAddress}}/api/User/register
Content-Type: application/json

{
  "email": "augustinseguin@gmail.com",
  "password": "MotDePasse123",
  "passwordRepeated": "MotDePasse123",
  "firstname": "leandra",
  "lastname": "DI GIUGNO",
  "username": "leandradiugno1",
  "birthdate": "2000-01-01T00:00:00Z",
  "gender": 0,
  "isPremium": false,
  "phoneNumber": 123456789,
  "isAdmin": true
}

###

### GET USER ME (auth)
GET {{ElixBackend_HostAddress}}/api/User/me
Authorization: Bearer {{token}}

###

### GET USER PICTURE (public)
GET {{ElixBackend_HostAddress}}/user/1/bec1f94f-d4a8-4593-a4c4-055b26459f4e.jpg

###

### GET USER BY ID (auth)
GET {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}

###

### UPDATE USER (auth)
PUT {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "email": "user@email.com",
  "password": "",
  "passwordRepeated": "",
  "firstname": "John",
  "lastname": "Doe",
  "username": "johndoe",
  "birthdate": "2000-01-01T00:00:00Z",
  "gender": 0,
  "isPremium": false,
  "phoneNumber": 123456789,
  "isAdmin": false
}

###

### UPDATE USER PICTURE (auth)
PUT {{ElixBackend_HostAddress}}/api/User/1/picture
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pictureFile"; filename="profile.jpg"
Content-Type: image/jpeg

< ./path/to/your/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

### DELETE USER (auth)
DELETE {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}

###

### LOGOUT (auth)
POST {{ElixBackend_HostAddress}}/api/User/logout
Authorization: Bearer {{token}}

###