@baseUrl = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0Iiwicm9sZSI6ImFkbWluIiwianRpIjoiMjIxMzI1ZGMtMTRlYy00NDJhLTk4YjQtOTk1M2I1YTE5M2MzIiwibmJmIjoxNzY3MDEwNDM3LCJleHAiOjE3NjcwMTc2MzcsImlhdCI6MTc2NzAxMDQzN30.oo9UbCKwC9Pz4kJ2xf_p6SNEOCV3Ng9-RZdtIhoRnzU

### Start a quiz
GET {{baseUrl}}/api/Quiz/StartQuiz?userId=1&categoryId=4
Authorization: Bearer {{token}}
Accept: application/json

### Submit quiz answer
POST {{baseUrl}}/api/Quiz/SubmitQuiz
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 1,
  "categoryId": 1,
  "userAnswers": [
    {
      "questionId": 1,
      "answerIdSelected": 1
    },
    {
      "questionId": 2,
      "answerIdSelected": 5
    },
    {
      "questionId": 3,
      "answerIdSelected": 9
    },
    {
      "questionId": 4,
      "answerIdSelected": 13
    },
    {
      "questionId": 5,
      "answerIdSelected": 17
    },
    {
      "questionId": 6,
      "answerIdSelected": 21
    },
    {
      "questionId": 7,
      "answerIdSelected": 25
    },
    {
      "questionId": 8,
      "answerIdSelected": 29
    },
    {
      "questionId": 9,
      "answerIdSelected": 33
    },
    {
      "questionId": 10,
      "answerIdSelected": 37
    }
  ]
}
