@baseUrl = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwicm9sZSI6ImFkbWluIiwianRpIjoiMzRjOWIyZGUtYmJiOC00NmI4LWI3OTMtNWUwOTk4MDFmY2ZlIiwibmJmIjoxNzY0Njg5NzExLCJleHAiOjE3NjQ2OTY5MTEsImlhdCI6MTc2NDY4OTcxMX0.kUQEyEHj2BUDcaWAe5JKZJg1L4Epth1RWfWWTVvQZI0

### Get all answers
GET {{baseUrl}}/api/Answer
Authorization: Bearer {{token}}
Accept: application/json

### Get answer by id
GET {{baseUrl}}/api/Answer/1
Authorization: Bearer {{token}}
Accept: application/json

### Create an answer (admin)
POST {{baseUrl}}/api/Answer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Réponse exemple",
  "questionId": 14,
  "isValid": false
}

### Update an answer (admin)
PUT {{baseUrl}}/api/Answer/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "title": "Réponse modifiée",
  "questionId": 1,
  "isValid": false
}

### Delete an answer (admin)
DELETE {{baseUrl}}/api/Answer/1
Authorization: Bearer {{token}}
