@baseUrl = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwicm9sZSI6ImFkbWluIiwianRpIjoiZjk5YThlOTktMjIxMC00Mjg2LTkwY2ItNGMwZWJlZDdjODJkIiwibmJmIjoxNzYyNzgyOTM5LCJleHAiOjE3NjI3OTAxMzksImlhdCI6MTc2Mjc4MjkzOX0.gzDMcSWR0xGct_ki0Gnp_6VwmDvfXF0fRiBXLPB2ECs

### Get all answers
GET {{baseUrl}}/api/Answer
Authorization: Bearer {{token}}
Accept: application/json

### Get answer by id
GET {{baseUrl}}/api/Answer/1
Authorization: Bearer {{token}}
Accept: application/json

### Create an answer (admin)
POST {{baseUrl}}/api/Answer
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Réponse exemple",
  "questionId": 1,
  "isValid": true
}

### Update an answer (admin)
PUT {{baseUrl}}/api/Answer/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "title": "Réponse modifiée",
  "questionId": 1,
  "isValid": false
}

### Delete an answer (admin)
DELETE {{baseUrl}}/api/Answer/1
Authorization: Bearer {{token}}
