@ElixBackend_HostAddress = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwicm9sZSI6ImFkbWluIiwianRpIjoiNDFjYzkzNTQtZDk2Yy00YWFlLTg1ZWItMjY4YjYzN2ExNGE1IiwibmJmIjoxNzY2MTU0MTIxLCJleHAiOjE3NjYxNjEzMjEsImlhdCI6MTc2NjE1NDEyMX0.tlq03gmUw-Roi8LUartuFTqRFap1MQ3JGvnpdL6_7gw

### LOGIN
POST {{ElixBackend_HostAddress}}/api/User/login
Content-Type: application/json

{
  "email": "us1er@email.com",
  "password": "MotDePasse123"
}

###

### REGISTER
POST {{ElixBackend_HostAddress}}/api/User/register
Content-Type: application/json

{
  "email": "us1Aer@email.com",
  "password": "MotDePasse123",
  "passwordRepeated": "MotDePasse123",
  "firstname": "John",
  "lastname": "Doe",
  "username": "johnAdoe1",
  "birthdate": "2000-01-01T00:00:00",
  "gender": 0,
  "isPremium": false,
  "phoneNumber": 123456789,
  "isAdmin": true
}

###

### GET USER ME (auth)
GET {{ElixBackend_HostAddress}}/api/User/me
Authorization: Bearer {{token}}

###

### GET USER BY ID (auth)
GET {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}

###

### UPDATE USER (auth)
PUT {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "email": "user@email.com",
  "password": "MotDePasse123",
  "passwordRepeated": "MotDePasse123",
  "firstname": "John",
  "lastname": "Doe",
  "username": "johndoe",
  "birthdate": "2000-01-01T00:00:00",
  "gender": 0,
  "isPremium": false,
  "phoneNumber": 123456789,
  "isAdmin": false
}

###

### DELETE USER (auth)
DELETE {{ElixBackend_HostAddress}}/api/User/1
Authorization: Bearer {{token}}

###

### LOGOUT (auth)
POST {{ElixBackend_HostAddress}}/api/User/logout
Authorization: Bearer {{token}}

###