@baseUrl = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwicm9sZSI6ImFkbWluIiwianRpIjoiMzRjOWIyZGUtYmJiOC00NmI4LWI3OTMtNWUwOTk4MDFmY2ZlIiwibmJmIjoxNzY0Njg5NzExLCJleHAiOjE3NjQ2OTY5MTEsImlhdCI6MTc2NDY4OTcxMX0.kUQEyEHj2BUDcaWAe5JKZJg1L4Epth1RWfWWTVvQZI0

### Get all questions
GET {{baseUrl}}/api/Question
Authorization: Bearer {{token}}
Accept: application/json

### Get question by id
GET {{baseUrl}}/api/Question/1
Authorization: Bearer {{token}}
Accept: application/json

### Create a question (admin)
POST {{baseUrl}}/api/Question
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Exemple de question",
  "categoryId": 1,
  "mediaPath": ""
}

### Update a question (admin)
PUT {{baseUrl}}/api/Question/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "title": "Question mise à jour",
  "categoryId": 1,
  "mediaPath": "/media/updated.png"
}

### Delete a question (admin)
DELETE {{baseUrl}}/api/Question/1
Authorization: Bearer {{token}}
