@ElixBackend_HostAddress = http://localhost:5059
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI0Iiwicm9sZSI6ImFkbWluIiwianRpIjoiODk2MTU4N2MtNjc4Zi00YjQ2LTlhMTQtZTQ0NDcyMTY2MTU0IiwibmJmIjoxNzY3MDA5NDc3LCJleHAiOjE3NjcwMTY2NzcsImlhdCI6MTc2NzAwOTQ3N30.7jJXubfaBndcNOi_iRCxd_KMj8n1GWV6QF2KmzxSI5k

### GET ALL CATEGORIES (auth)
GET {{ElixBackend_HostAddress}}/api/Category
Authorization: Bearer {{token}}

###

### GET CATEGORY BY ID (auth)
GET {{ElixBackend_HostAddress}}/api/Category/1
Authorization: Bearer {{token}}

###

### CREATE CATEGORY (auth)
POST {{ElixBackend_HostAddress}}/api/Category
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Nouvelle catégorie",
  "description": "Description de la catégorie"
}

###

### UPDATE CATEGORY (auth)
PUT {{ElixBackend_HostAddress}}/api/Category/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "Catégorie modifiée",
  "description": "Nouvelle description"
}

###

### UPDATE CATEGORY IMAGE (auth)
PUT {{ElixBackend_HostAddress}}/api/Category/1/image
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imageFile"; filename="category.jpg"
Content-Type: image/jpeg

< ./path/to/your/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

### GET CATEGORY IMAGE (public)
GET {{ElixBackend_HostAddress}}/category/1/image-filename.jpg

###

### DELETE CATEGORY (auth)
DELETE {{ElixBackend_HostAddress}}/api/Category/1
Authorization: Bearer {{token}}

###